version: '3'
services:
#  database:
#    image: postgres
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
  ruby:
    build: .
    volumes:
      - .:/data/app
    ports:
      - 3000:3000
    links:
      - mailcatcher

  mailcatcher:
    build: .docker/mailcatcher
    ports:
      - 1080:1080